---
title: "precipitation data processing for tropical storm"
author: "Rakib"
date: "2025-03-21"
output: html_document
---
#library
```{r}
library(tidygeocoder)
library(dplyr)
library(stringr)
```

#elsa
```{r}
preci <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/elsa.csv")
#getting station address
preci <- preci %>%
  reverse_geocode(lat = LATITUDE, long = LONGITUDE, method = "osm") # OpenStreetMap API
#getting county name from address
county_names <- str_extract(preci$address, "\\b([A-Za-z ]+ County)\\b(?=, Florida)")
#Adding county name col in the data
preci$county <- county_names
#check unique county
length(unique(preci$county))#should be 67, but we have 65
######missing counties
#loading population data file to check counties
population <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/population/fl_population_2020.csv")
#checking missing county
extracted_preci <- unique(preci$county)
extracted_population <- population$NAME
#removing word ', Florida' from population data file
extracted_population <- str_remove(extracted_population, ", Florida")
#checking missing county
setdiff(extracted_preci, extracted_population)
setdiff(extracted_population, extracted_preci)
#replacing "Dade County" to "Miami-Dade County", "Saint Lucie County" to "St. Lucie County" and "Saint Johns County" to "St. Johns County"
preci <- preci %>%
  mutate(county = str_replace_all(county, 
                                  c("Dade County" = "Miami-Dade County",
                                    "Saint Johns County"= "St. Johns County",
                                    "Saint Lucie County" = "St. Lucie County")))
#missing checking again
extracted_preci <- unique(preci$county)
setdiff(extracted_population, extracted_preci)

#extracting precipitation data
preci <- preci[,c("STATION", "NAME", "county", "DATE", "PRCP")]
#aggregate
aggregated_preci <- preci %>%
  group_by(DATE, county) %>%
  summarise(
    max_prcp = ifelse(all(is.na(PRCP)), NA, max(PRCP, na.rm = TRUE)),  # Take max value, ignore NA
    min_prcp = ifelse(all(is.na(PRCP)), NA, min(PRCP, na.rm = TRUE)),  # Take min value, ignore NA
    mean_prcp = ifelse(all(is.na(PRCP)), NA, mean(PRCP, na.rm = TRUE)),  # Take mean value, ignore NA
  )
#removing NA
aggregated_preci <- na.omit(aggregated_preci)
#unique counties & records
unique(aggregated_preci$county)
length(aggregated_preci$DATE)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed")
write.csv(aggregated_preci,'elsa.csv', row.names = F)
```

#eta
```{r}
preci <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/eta.csv")
#getting station address
preci <- preci %>%
  reverse_geocode(lat = LATITUDE, long = LONGITUDE, method = "osm") # OpenStreetMap API
#getting county name from address
county_names <- str_extract(preci$address, "\\b([A-Za-z ]+ County)\\b(?=, Florida)")
#Adding county name col in the data
preci$county <- county_names
#check unique county
length(unique(preci$county))#should be 67, but we have 65
######missing counties
#loading population data file to check counties
population <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/population/fl_population_2020.csv")
#checking missing county
extracted_preci <- unique(preci$county)
extracted_population <- population$NAME
#removing word ', Florida' from population data file
extracted_population <- str_remove(extracted_population, ", Florida")
#checking missing county
setdiff(extracted_preci, extracted_population)
setdiff(extracted_population, extracted_preci)
#replacing "Dade County" to "Miami-Dade County", "Saint Lucie County" to "St. Lucie County" and "Saint Johns County" to "St. Johns County"
preci <- preci %>%
  mutate(county = str_replace_all(county, 
                                  c("Dade County" = "Miami-Dade County",
                                    "Saint Johns County"= "St. Johns County",
                                    "Saint Lucie County" = "St. Lucie County")))
#missing checking again
extracted_preci <- unique(preci$county)
setdiff(extracted_population, extracted_preci)

#extracting precipitation data
preci <- preci[,c("STATION", "NAME", "county", "DATE", "PRCP")]
#aggregate
aggregated_preci <- preci %>%
  group_by(DATE, county) %>%
  summarise(
    max_prcp = ifelse(all(is.na(PRCP)), NA, max(PRCP, na.rm = TRUE)),  # Take max value, ignore NA
    min_prcp = ifelse(all(is.na(PRCP)), NA, min(PRCP, na.rm = TRUE)),  # Take min value, ignore NA
    mean_prcp = ifelse(all(is.na(PRCP)), NA, mean(PRCP, na.rm = TRUE)),  # Take mean value, ignore NA
  )
#removing NA
aggregated_preci <- na.omit(aggregated_preci)
#unique counties & records
unique(aggregated_preci$county)
length(aggregated_preci$DATE)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed")
write.csv(aggregated_preci,'eta.csv', row.names = F)
```

#fred
```{r}
preci <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/fred.csv")
#getting station address
preci <- preci %>%
  reverse_geocode(lat = LATITUDE, long = LONGITUDE, method = "osm") # OpenStreetMap API
#getting county name from address
county_names <- str_extract(preci$address, "\\b([A-Za-z ]+ County)\\b(?=, Florida)")
#Adding county name col in the data
preci$county <- county_names
#check unique county
length(unique(preci$county))#should be 67, but we have 65
######missing counties
#loading population data file to check counties
population <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/population/fl_population_2020.csv")
#checking missing county
extracted_preci <- unique(preci$county)
extracted_population <- population$NAME
#removing word ', Florida' from population data file
extracted_population <- str_remove(extracted_population, ", Florida")
#checking missing county
setdiff(extracted_preci, extracted_population)
setdiff(extracted_population, extracted_preci)
#replacing "Dade County" to "Miami-Dade County", "Saint Lucie County" to "St. Lucie County" and "Saint Johns County" to "St. Johns County"
preci <- preci %>%
  mutate(county = str_replace_all(county, 
                                  c("Dade County" = "Miami-Dade County",
                                    "Saint Johns County"= "St. Johns County",
                                    "Saint Lucie County" = "St. Lucie County")))
#missing checking again
extracted_preci <- unique(preci$county)
setdiff(extracted_population, extracted_preci)

#extracting precipitation data
preci <- preci[,c("STATION", "NAME", "county", "DATE", "PRCP")]
#aggregate
aggregated_preci <- preci %>%
  group_by(DATE, county) %>%
  summarise(
    max_prcp = ifelse(all(is.na(PRCP)), NA, max(PRCP, na.rm = TRUE)),  # Take max value, ignore NA
    min_prcp = ifelse(all(is.na(PRCP)), NA, min(PRCP, na.rm = TRUE)),  # Take min value, ignore NA
    mean_prcp = ifelse(all(is.na(PRCP)), NA, mean(PRCP, na.rm = TRUE)),  # Take mean value, ignore NA
  )
#removing NA
aggregated_preci <- na.omit(aggregated_preci)
#unique counties & records
unique(aggregated_preci$county)
length(aggregated_preci$DATE)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed")
write.csv(aggregated_preci,'fred.csv', row.names = F)
```

#mindy
```{r}
preci <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/mindy.csv")
#getting station address
preci <- preci %>%
  reverse_geocode(lat = LATITUDE, long = LONGITUDE, method = "osm") # OpenStreetMap API
#getting county name from address
county_names <- str_extract(preci$address, "\\b([A-Za-z ]+ County)\\b(?=, Florida)")
#Adding county name col in the data
preci$county <- county_names
#check unique county
length(unique(preci$county))#should be 67, but we have 65
######missing counties
#loading population data file to check counties
population <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/population/fl_population_2020.csv")
#checking missing county
extracted_preci <- unique(preci$county)
extracted_population <- population$NAME
#removing word ', Florida' from population data file
extracted_population <- str_remove(extracted_population, ", Florida")
#checking missing county
setdiff(extracted_preci, extracted_population)
setdiff(extracted_population, extracted_preci)
#replacing "Dade County" to "Miami-Dade County", "Saint Lucie County" to "St. Lucie County" and "Saint Johns County" to "St. Johns County"
preci <- preci %>%
  mutate(county = str_replace_all(county, 
                                  c("Dade County" = "Miami-Dade County",
                                    "Saint Johns County"= "St. Johns County",
                                    "Saint Lucie County" = "St. Lucie County")))
#missing checking again
extracted_preci <- unique(preci$county)
setdiff(extracted_population, extracted_preci)

#extracting precipitation data
preci <- preci[,c("STATION", "NAME", "county", "DATE", "PRCP")]
#aggregate
aggregated_preci <- preci %>%
  group_by(DATE, county) %>%
  summarise(
    max_prcp = ifelse(all(is.na(PRCP)), NA, max(PRCP, na.rm = TRUE)),  # Take max value, ignore NA
    min_prcp = ifelse(all(is.na(PRCP)), NA, min(PRCP, na.rm = TRUE)),  # Take min value, ignore NA
    mean_prcp = ifelse(all(is.na(PRCP)), NA, mean(PRCP, na.rm = TRUE)),  # Take mean value, ignore NA
  )
#removing NA
aggregated_preci <- na.omit(aggregated_preci)
#unique counties & records
unique(aggregated_preci$county)
length(aggregated_preci$DATE)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed")
write.csv(aggregated_preci,'mindy.csv', row.names = F)
```

# combining
```{r}
#loading precipitation data
elsa <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed/elsa.csv")
eta <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed/eta.csv")
fred <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed/fred.csv")
mindy <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed/mindy.csv")
#combining
preci <- bind_rows(elsa, eta, fred, mindy)
#unique counties & records
unique(preci$county)
length(preci$DATE)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/tropical strom/precipitation/processed")
write.csv(preci,'preci_tropical.csv', row.names = F)
```

