---
title: "event outage data processing and adding day difference, hurricane"
author: "Rakib"
date: "2025-05-09"
output: html_document
---

# library
```{r}
library(dplyr)
```

# Idalia, 2023-08-30
```{r}
#loading season data
outage <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/outage season data/2023_s.csv")
#extracting dates around the event
event_date <- as.Date('2023-08-30')
str(outage)
outage$date <- as.Date(outage$date)

outage <- outage %>%
  filter(date>=event_date-3 & date<=event_date+14)
summary(outage)
#adding day difference
outage <- outage%>%
  mutate(day_difference=as.numeric(as.Date(date) - event_date))

#unique counties & records
unique(outage$county)
length(outage$date)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data")
write.csv(outage, 'idalia.csv', row.names = F)
##################################
#finding missing data 
all_dates <- as.Date(seq((event_date-3),(event_date+14),by='day'))
all_counties <- unique(outage$county)
expected_rows <- expand.grid(date = all_dates, county = all_counties)
length(expected_rows$date)
merged <- expected_rows %>%
  left_join(outage, by = c("date", "county"))
missing <- merged %>%
  filter(is.na(total_outage))
length(missing$date)
################################
```

# Ian, 2022-09-28
```{r}
#loading season data
outage <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/outage season data/2022_s.csv")
#extracting dates around the event
event_date <- as.Date('2022-09-28')
str(outage)
outage$date <- as.Date(outage$date)

outage <- outage %>%
  filter(date>=event_date-3 & date<=event_date+14)
summary(outage)
#adding day difference
outage <- outage%>%
  mutate(day_difference=as.numeric(as.Date(date) - event_date))
#unique counties & records
unique(outage$county)
length(outage$date)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data")
write.csv(outage, 'ian.csv', row.names = F)
##################################
#finding missing data 
all_dates <- as.Date(seq((event_date-3),(event_date+14),by='day'))
all_counties <- unique(outage$county)
expected_rows <- expand.grid(date = all_dates, county = all_counties)
length(expected_rows$date)
merged <- expected_rows %>%
  left_join(outage, by = c("date", "county"))
missing <- merged %>%
  filter(is.na(total_outage))
length(missing$date)
################################
```

# Nicole, 2022-11-10
```{r}
#loading season data
outage <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/outage season data/2022_s.csv")
#extracting dates around the event
event_date <- as.Date('2022-11-10')
str(outage)
outage$date <- as.Date(outage$date)

outage <- outage %>%
  filter(date>=event_date-3 & date<=event_date+14)
summary(outage)
#adding day difference
outage <- outage%>%
  mutate(day_difference=as.numeric(as.Date(date) - event_date))
#unique counties & records
unique(outage$county)
length(outage$date)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data")
write.csv(outage, 'nicole.csv', row.names = F)
##################################
#finding missing data 
all_dates <- as.Date(seq((event_date-3),(event_date+14),by='day'))
all_counties <- unique(outage$county)
expected_rows <- expand.grid(date = all_dates, county = all_counties)
length(expected_rows$date)
merged <- expected_rows %>%
  left_join(outage, by = c("date", "county"))
missing <- merged %>%
  filter(is.na(total_outage))
length(missing$date)
################################
```

# Sally, 2020-09-16
```{r}
outage <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/outage season data/2020_s.csv")
str(outage)
#adding total outage by customer col (in hour)
outage$total_outage_by_customers <- ifelse(is.na(outage$customers_out),NA, outage$customers_out*0.25)
#aggregating
outage <- outage %>%
  group_by(fips_code, county, date) %>%
  summarise(
    total_outage = ifelse(all(is.na(total_outage_by_customers)), NA, sum(total_outage_by_customers, na.rm = TRUE)),
    .groups = "drop"
  )
#extracting dates around the event
event_date <- as.Date('2020-09-16')
str(outage)
outage$date <- as.Date(outage$date)

outage <- outage %>%
  filter(date>=event_date-3 & date<=event_date+14)

###fixing 0 outage as there is no entry during 0 outage
all_counties <- unique(outage$county)
all_date <- as.Date(seq((event_date-3),(event_date+14),by='day'))
expected_rows <- expand.grid(date = all_date, county = all_counties)
#NA values
na <- outage %>%
  filter(is.na(total_outage))
length(na$date)
#finding missing
merged <- expected_rows %>%
  left_join(outage, by = c("date", "county"))
missing <- merged %>%
  filter(is.na(total_outage))
#putting 0 total outage after removing na
outage_0 <- anti_join(missing, na, by=c('date', 'county'))
outage_0 <- outage_0 %>%
  mutate(total_outage=0)
#adding fips code
fips_unique <- outage %>%
  select(county, fips_code) %>%
  distinct(county, .keep_all = TRUE)  # Keeps only the first occurrence
outage_0 <- outage_0 %>%
  left_join(fips_unique, by = "county") %>%   # Merge
  mutate(fips_code = coalesce(fips_code.x, fips_code.y)) %>%  # Replace missing values
  select(-fips_code.x, -fips_code.y)  # Remove extra columns
#adding o outage
outage <- bind_rows(outage, outage_0)
#removing NA
outage <- anti_join(outage, na, by=c('date', 'county'))
#adding day difference
outage <- outage%>%
  mutate(day_difference=as.numeric(as.Date(date) - event_date))
#unique counties & records
unique(outage$county)
length(outage$date)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data")
write.csv(outage, 'sally.csv', row.names = F)
```

# Combined
```{r}
idalia <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data/idalia.csv")
ian <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data/ian.csv")
nicole <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data/nicole.csv")
sally <- read.csv("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data/sally.csv")
#combining
hurricane <- bind_rows(idalia, ian, nicole, sally)
summary(hurricane)
#unique counties & records
unique(hurricane$county)
length(hurricane$date)
#saving
setwd("C:/Users/rakib/Desktop/Thesis/DATA/hurricane/event outage data")
write.csv(hurricane, 'hurricane_outage.csv', row.names = F)
```

